version: "3.8"

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "3050:80"
    networks:
      - postgres

  api:
    build:
      dockerfile: Dockerfile
      context: "../server"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ../server:/app
    networks:
      - postgres

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ../client
    volumes:
      - /app/node_modules
      - ../client:/app
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
